#!/bin/sh
#
# -*-sh-*-
#
#     Copyright (C) 2011  Maximilian Mehnert <maximilian.mehnert@gmx.de>
# 
#     This program is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 2 of the License, or
#     (at your option) any later version.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with this program; if not, write to the Free Software Foundation,
#     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301,, USA.

#   Put this into your .libdbrc:

#MODULES_PATH="$MODULES_PATH /ABSOLUTE_PATH_TO_THIS_DIRECTORY"
#METHODS=m_tbabook
#TbAbookListerPath=/ABSOLUTE_PATH_TO_THIS_DIRECTORY
#TB_ABOOKS="/ABSOLUTE_PATHS_TO_TB_ADDRESSBOOK_FILE_A.mab /ABSOLUTE_PATHS_TO_TB_ADDRESSBOOK_FILE_N.mab"

m_tbabook_query()
{
    if [ ! -z "$@" ]; then
        $TbAbookListerPath/TbAbookListAddresses.py $TB_ABOOKS|grep -ia $@
    else
        $TbAbookListerPath/TbAbookListAddresses.py $TB_ABOOKS
    fi

}

